# Generated by Django 3.1.7 on 2021-08-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('optional_description', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(verbose_name='creation_date')),
                ('owner', models.CharField(max_length=30)),
                ('validity_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('optional_description', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(verbose_name='creation_date')),
                ('owner', models.CharField(max_length=30)),
                ('validity_flag', models.BooleanField()),
                ('directory_name', models.CharField(max_length=50)),
                ('filepath', models.FileField(upload_to='files', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='File_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('optional_description', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(verbose_name='date_published')),
                ('owner', models.CharField(max_length=30)),
                ('validity_flag', models.BooleanField()),
                ('file', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FramaOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('output', models.CharField(max_length=30000)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('login_1', models.CharField(blank=True, max_length=50)),
                ('login_2', models.CharField(blank=True, max_length=50)),
                ('creation_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='Group_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('coowner', models.CharField(max_length=100)),
                ('optional_description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('validity_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('optional_description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('validity_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Section_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('validity_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('validity_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data_field', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
        migrations.CreateModel(
            name='Section_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_data_field', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('validity_flag', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
