# Generated by Django 3.1.7 on 2021-04-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_file_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='creation_date',
            field=models.DateTimeField(verbose_name='creation_date'),
        ),
    ]
