# Generated by Django 3.1.7 on 2021-04-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210430_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='FramaOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('output', models.CharField(max_length=30000)),
            ],
        ),
    ]
