# Generated by Django 3.1.7 on 2021-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_framaoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('login_1', models.CharField(blank=True, max_length=50)),
                ('login_2', models.CharField(blank=True, max_length=50)),
                ('creation_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='Group_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('coowner', models.CharField(max_length=100)),
                ('optional_description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('validity_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('optional_description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('validity_flag', models.BooleanField()),
            ],
        ),
    ]
