# Generated by Django 3.1.7 on 2021-07-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_group_group_project_group_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_task',
            name='optional_description',
        ),
    ]
